### ISSUE TITLE
On compile success of sass/scss, the result is an object 

### ISSUE THREAD

**Issue by eduardhojbota** [electronjs/electron-compile#12]
I've been trying to compile sass/scss with electron-compile but all I get is an object. See the attached image.
![screen shot 2015-07-25 at 9 49 01 am](https://cloud.githubusercontent.com/assets/2820538/8888348/99755a34-32b2-11e5-96dc-7e3a5f40423e.png)

**Comment by paulcbetts** [comment]
@eduardhojbota Can you share your SCSS? We should add it as a test case

**Comment by eduardhojbota** [comment]
I was setting the base for my project, so the file did not contain much really, just test code for livereload.

main.scss
```scss
h1 {
  color: green;
}
```

main.sass
```sass
h1
  color: green
```

**Comment by paulcbetts** [comment]
Yep, looks like a bug in the Sass compiler, thanks for the report. This is fixed in electron-compile 0.7.2
