### ISSUE TITLE
Error on Electron Startup

### ISSUE THREAD

**Issue by daekano** [electronjs/electron-compile#19]
With `require('electron-compile').init();` as the first statement in my main.js file, Electron pops up an alert with the following text:

```
A JavaScript error occured in the main process.

Uncaught Exception:
Error: The Scheme is already registered
    at Error (native)
```

Commenting out the electron-compile init results in the application running smoothly.

**Comment by minivan** [comment]
I get the same error when I run `npm start`. (my package.json has `  "start": "electron ." `)

However, when I run `electron .` in my app's directory, it works OK.

**Comment by jean-emmanuel** [comment]
Same error here (v0.30.4)

**Comment by paulcbetts** [comment]
You probably need to stay on v0.30.2 until I can update `electron-compile` to be compatible

**Comment by jean-emmanuel** [comment]
Alright then !

**Comment by paulcbetts** [comment]
This is actually easier than I thought it would be to fix, done!

**Comment by bshy522** [comment]
nice!

**Comment by daekano** [comment]
Awesome! Nice work :)
