### ISSUE TITLE
InterceptProtocol has been replaced by new API

### ISSUE THREAD

**Issue by faurehu** [electronjs/electron-compile#22]
Just by calling `init()` in my `main.js` file I get this error:
`interceptProtocol API has been replaced by the intercept[File/Http/Buffer/String]Protocol API family, please switch to the new APIs.`

Electron's protocol documentation has changed. [Here](https://github.com/atom/electron/commit/7d97bb6fe0a6feef886d927ea894bcb2f3521577) is the commit so you can see the new names for the given functions.

**Comment by paulcbetts** [comment]
electron-compile isn't compatible with Electron 0.31.x yet, but it will be soon. In the meantime, downgrade to 0.30.x

**Comment by faurehu** [comment]
Thanks for clarifying.

**Comment by paulcbetts** [comment]
Let's leave this issue open until we fix it
