### ISSUE TITLE
LESS Sourcemaps not being used 

### ISSUE THREAD

**Issue by nourikhalass** [electronjs/electron-compile#29]
When initializing the compiler in the following way:
```javascript
require('electron-compile').
    initWithOptions({
        compilerOpts: {
            // Compiler options are a map of extension <=> options for compiler
            less: {
                sourceMap: {
                    sourceMapFileInline: true
                }
            }
        }
});
```

The compiler compiles the LESS correctly with the sourcemap code inlined but the map is not used.

Versions:
chrome: "45.0.2454.85"
electron: "0.33.6"
node: "4.1.1"

**Comment by paulcbetts** [comment]
This is probably an Electron bug, not much we can do about it unless you figure out we're generating incorrect source map info
