### ISSUE TITLE
precompiling for production

### ISSUE THREAD

**Issue by maxkorp** [electronjs/electron-compile#33]
I have 2 issues/questions with precompiling for production
Firstly, how do I pass options? I've ended up having to basically reimplement the CLI file in my project with the slight modification of calling initWithOptions (and passing in my options) instead of just calling init.

Secondly, running in production mode just flat out isn't working. I point it at the same cachedir, but it will load a few things in production (my main process stuff is ok), but my renderer processes wont load. Flipping it to use initwithoptions works fine. Subsequently flipping it back (in case something wasnt compiled) remains broken.

**Comment by maxkorp** [comment]
Further investigation yields that swapping `createProductionCompilersForInfo` to a `createallcompilers` works makes it work, so it's definitely something with the production readonly compilers.

**Comment by paulcbetts** [comment]
> Firstly, how do I pass options? I've ended up having to basically reimplement the CLI file in my project with the slight modification of calling initWithOptions (and passing in my options) instead of just calling init.

Yeah, this is definitely something we should improve in #31 

> Secondly, running in production mode just flat out isn't working. I point it at the same cachedir, but it will load a few things in production (my main process stuff is ok), but my renderer processes wont load. Flipping it to use initwithoptions works fine.

Is it possible that we're not correctly passing down compiler options to the renderer?

**Comment by maxkorp** [comment]
Possibly. I'm working at trying to figure out where it dies, but it doesn't appear it even opens a window for me (although thats plausibly my code's fault).

**Comment by paulcbetts** [comment]
This should be 1000% better in 2.0, fixed!
