### ISSUE TITLE
CoffeeScript included inside Jade template compiles fine, but never executes

### ISSUE THREAD

**Issue by ezekg** [electronjs/electron-compile#54]
I'm attempting to migrate an existing app I've been working on to `2.0`, but I'm not sure what's going on here. I have this Jade file:

```jade
doctype
html
  head
    meta(charset="UTF-8")
    title Test App
    link(rel="stylesheet" type="text/less" href="index.less")
  body
    script(type="text/coffeescript" src="index.coffee")
```

My `.compilerc` file:
```json
{
  "application/javascript": {
    "presets": ["stage-0", "es2015", "react"],
    "sourceMaps": "inline"
  },
  "text/coffeescript": {
    "sourceMap": true
  },
  "text/less": {
    "dumpLineNumbers": "comments"
  }
}
```

The LESS compiles fine and executes correctly (testing by coloring the `body` background gray). However, the CoffeeScript _compiles_ fine, but is never executed (testing by doing a `console.log`). I can see that the network request was successfully made, and that it is returning valid JavaScript, but it is never included within the sources panel (headers are `application/javascript`, which is correct).

The network tab:
![image](https://cloud.githubusercontent.com/assets/6979737/12181555/9438d168-b548-11e5-8459-126f17169b62.png)

The sources tab:
![image](https://cloud.githubusercontent.com/assets/6979737/12181444/d6a6fd14-b547-11e5-96bc-0d312e11006a.png)

I can write inline CoffeeScript fine, but including via a `script` tag never works.

Any ideas on what's going on?

**Comment by ezekg** [comment]
It gets even weird... I tried changing the script type to `application/javascript` and it compiles to JS fine, but all required modules from within `index.coffee` do not get compiled. Any idea what would causing this? Even after digging into the code for this lib, I still can't figure out what's causing the issue.

**Comment by paulcbetts** [comment]
Weird, can you share an example app?

**Comment by ezekg** [comment]
Definitely. I'll work on getting a small example app up today.

**Comment by ezekg** [comment]
[Here you go](https://github.com/ezekg/electron-example-app).

**Comment by paulcbetts** [comment]
@ezekg So, for external `script` tags, don't include the `type` attribute. I'll fix this to rig it explicitly, but you only need to include the `type` attribute for inline scripts. Getting this behavior right is tricky because some people do stuff like include Handlebars templates as script tags, which we don't want to touch.

**Comment by ezekg** [comment]
@paulcbetts, that's what I thought, but if I do that, none of the modules resolve. The line [`require "../main/main"`](https://github.com/ezekg/electron-example-app/blob/master/src/renderer/index.coffee?ts=2#L1) results in an error (you can append `.coffee` to the line and it resolves, but doesn't compile into JS, resulting in an error):

```
Uncaught Error: Cannot find module '../main/main'
Module._resolveFilename
@ module.js:338Module._load
@ module.js:289Module.require
@ module.js:366require
@ module.js:385(anonymous function)
@ index.coffee:1
```

It's almost like after the initial `require`, the `required`'d files are no longer compiled. There's gotta be a deeper issue here. I'll dig in more tomorrow. I'd love to get this resolved, as I'm really interested in helping out with this whole project. The app works fine with electron-compile `1.x`, so it has to be something introduced in `2.x` (that's assuming you didn't rewrite the library; I haven't looked at the repo history).

**Comment by paulcbetts** [comment]
Aha, if you include a Jade file, we don't do the fixup in https://github.com/electronjs/electron-compile/blob/master/src/protocol-hook.js#L157. Good catch.

**Comment by paulcbetts** [comment]
2.0.5 is published to fix this bug!

**Comment by paulcbetts** [comment]
> that's assuming you didn't rewrite the library; I haven't looked at the repo history

2.x is basically a total rewrite of electron-compile, yeah :)

**Comment by ezekg** [comment]
Woooo! Confirmed working. :tada: Thanks.
