### ISSUE TITLE
unable to require relative on client

### ISSUE THREAD

**Issue by jronallo** [electronjs/electron-compile#60]
I have some CoffeeScript which is loaded via a script tag onto an HTML page. That works and is compiled just fine. Within the client-side CoffeeScript file I try to require a module from another CoffeeScript file I've created that is in the same directory. It seems as if the path that is given to a compiled CoffeeScript file is the same as the path to the directory that includes the HTML file. Instead of being able to use `require('./other_coffeescript_file')` I needed to use something more specific like `require("#{__dirname}/../javascripts/other_coffeescript_file")`.

I'm probably not organizing my application as a normal node or electron app or might have missed something else, but thought you ought to know about this in case there is something you might want to add to the documentation.

**Comment by paulcbetts** [comment]
When you include a file via a script tag, Electron doesn't set up a module for it, so the path will be relative to the opening HTML page. To avoid this, do something like:

```
<script>require('../mymodule/relative/to/HTML/page')</script>
```

Then modules that _that_ module requires will act the way you expect

**Comment by jronallo** [comment]
Thank you for the explanation.
